Add working pytest script

diff --git a/components/aws/sagemaker/tests/integration_tests/scripts/run_integration_tests b/components/aws/sagemaker/tests/integration_tests/scripts/run_integration_tests
--- a/components/aws/sagemaker/tests/integration_tests/scripts/run_integration_tests
+++ b/components/aws/sagemaker/tests/integration_tests/scripts/run_integration_tests
@@ -8,18 +8,27 @@ usage(){
 	exit 1
 }
 
+cwd=$(dirname $(realpath $0))
+
 ### Input parameters
 DEPLOY_NAME="sagemaker-kfp-"$(date '+%Y-%m-%d-%H-%M-%S')"" # The name given to the entire deployment (tagging all resources)
-REGION=`aws configure get region` # Deployment region
+REGION=${REGION:-"$(aws configure get region)"} # Deployment region
 
 ### Configuration parameters
-EKS_CLUSTER_VERSION="1.15" # EKS cluster K8s version
-EKS_NODE_COUNT="1" # The initial node count of the EKS cluster
+EKS_EXISTING_CLUSTER=${EKS_EXISTING_CLUSTER:-""} # Use an existing EKS cluster
+EKS_CLUSTER_VERSION=${EKS_CLUSTER_VERSION:-"1.15"} # EKS cluster K8s version
+EKS_NODE_COUNT=${EKS_NODE_COUNT:-"1"} # The initial node count of the EKS cluster
 EKS_PUBLIC_SUBNETS=${EKS_PUBLIC_SUBNETS:-""}
 EKS_PRIVATE_SUBNETS=${EKS_PRIVATE_SUBNETS:-""}
 
 ### Testing parameters
-MINIO_LOCAL_PORT=9000
+MINIO_LOCAL_PORT=${MINIO_LOCAL_PORT:-9000}
+KFP_NAMESPACE=${KFP_NAMESPACE:-"kubeflow"}
+KFP_SERVICE_ACCOUNT=${KFP_SERVICE_ACCOUNT:-"pipeline-runner"}
+
+PYTEST_MARKER=${PYTEST_MARKER:-""}
+S3_DATA_BUCKET=${S3_DATA_BUCKET:-"kfp-test-data"}
+SAGEMAKER_EXECUTION_ROLE_ARN=${SAGEMAKER_EXECUTION_ROLE_ARN:-""}
 
 while getopts ":n:r:" opt; do
   case $opt in
@@ -47,20 +56,22 @@ if [ "$DEPLOY_NAME" == "" ]; then
   exit 1
 fi
 
-cleanup() {
+function cleanup() {
   set +e
 
   cleanup_kfp
   delete_generated_role
-  delete_eks
+
+  if [[ -z "${EKS_EXISTING_CLUSTER}" ]]; then
+    delete_eks
+  fi
 }
 
-# Set the trap to clean up resources
-# In case of error or normal exit delete the cluster
+# Set the trap to clean up resources in the case of an error
 trap cleanup EXIT
 set -e
 
-launch_eks() {
+function launch_eks() {
   EKS_CLUSTER_NAME="${DEPLOY_NAME}-eks-cluster"
 
   echo "[Creating EKS] Launching EKS cluster $EKS_CLUSTER_NAME"
@@ -69,18 +80,18 @@ launch_eks() {
   [ ! -z "${EKS_PUBLIC_SUBNETS}" ] && eksctl_args+=( --vpc-public-subnets="${EKS_PUBLIC_SUBNETS}" )
   [ ! -z "${EKS_PRIVATE_SUBNETS}" ] && eksctl_args+=( --vpc-private-subnets="${EKS_PRIVATE_SUBNETS}" )
 
-  eksctl create cluster "${EKS_CLUSTER_NAME}"
+  eksctl create cluster "${EKS_CLUSTER_NAME}" "${eksctl_args[@]}"
 
   aws eks update-kubeconfig --name "$EKS_CLUSTER_NAME" --region "$REGION"
 
   echo "[Creating EKS] $EKS_CLUSTER_NAME launched"
 }
 
-delete_eks() {
+function delete_eks() {
   eksctl delete cluster --name "${EKS_CLUSTER_NAME}"
 }
 
-install_kfp() {
+function install_kfp() {
   echo "[Installing KFP] Applying KFP manifests"
 
   PIPELINE_VERSION=0.5.1
@@ -96,26 +107,44 @@ install_kfp() {
   echo "[Installing KFP] Minio port-forwarded to ${MINIO_LOCAL_PORT}"
 }
 
-function generate_iam_role_name {
-  local cluster=$(echo "${cluster_name}" | cut -d'/' -f2)
-
-  OIDC_ROLE_NAME="$(echo "${cluster}-kubeflow-role" | cut -c1-64)"
+function generate_iam_role_name() {
+  OIDC_ROLE_NAME="$(echo "${DEPLOY_NAME}-kubeflow-role" | cut -c1-64)"
+  OIDC_ROLE_ARN="arn:aws:iam::$(aws sts get-caller-identity --query=Account --output=text):role/${OIDC_ROLE_NAME}"
 }
 
-function delete_generated_role {
+function install_generated_role() {
+  kubectl patch serviceaccount -n ${KFP_NAMESPACE} ${KFP_SERVICE_ACCOUNT} --patch '{"metadata": {"annotations": {"eks.amazonaws.com/role-arn": "'"${OIDC_ROLE_ARN}"'"}}}'
+}
+
+function delete_generated_role() {
   # Delete the role associated with the cluster thats being deleted
   aws iam detach-role-policy --role-name "${OIDC_ROLE_NAME}" --policy-arn arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
   aws iam delete-role --role-name "${OIDC_ROLE_NAME}"
 }
 
-cleanup_kfp() {
+function cleanup_kfp() {
   # Clean up Minio
   if [[ ! -z "${MINIO_PID}" ]]; then
     kill -9 $MINIO_PID
   fi
 }
 
-launch_eks
+if [[ -z "${EKS_EXISTING_CLUSTER}" ]]; then
+  launch_eks
+else
+  aws eks update-kubeconfig --name "${EKS_EXISTING_CLUSTER}" --region "$REGION"
+  EKS_CLUSTER_NAME="${EKS_EXISTING_CLUSTER}"
+  DEPLOY_NAME="${EKS_EXISTING_CLUSTER}"
+fi
+
 generate_iam_role_name
-./generate_iam_role ${EKS_CLUSTER_NAME} ${OIDC_ROLE_NAME} ${REGION} "kubeflow" "pipeline-runner"
+"$cwd"/generate_iam_role ${EKS_CLUSTER_NAME} ${OIDC_ROLE_NAME} ${REGION} ${KFP_NAMESPACE} ${KFP_SERVICE_ACCOUNT}
 install_kfp
+install_generated_role
+
+set -x
+
+pytest_args=( --region "${REGION}" --role-arn "${SAGEMAKER_EXECUTION_ROLE_ARN}" --s3-data-bucket "${S3_DATA_BUCKET}" --minio-service-port "${MINIO_LOCAL_PORT}" --kfp-namespace "${KFP_NAMESPACE}" )
+[ ! -z "${PYTEST_MARKER}" ] && pytest_args+=( -m "${PYTEST_MARKER}" )
+
+cd tests/integration_tests && python -m pytest "${pytest_args[@]}" --junitxml ./integration_tests.log -n $(nproc)
